### ISSUE TITLE
java.lang.NoSuchMethodError when updating 0.13.10 to 0.13.12

### ISSUE THREAD

**Issue by voodoo84** [jchambers/pushy#863]
Hello,

I have a Maven project which use com.turo.pushy version 0.13.10, and then we decided to update to com.eatthepath.pushy 0.13.12 for bugfixes.

Both versions build fine, but 0.13.12 throws the following exception on startup when trying to construct ApnsClient:

`
java.lang.NoSuchMethodError: io.netty.util.internal.StringUtil.indexOfWhiteSpace(Ljava/lang/CharSequence;I)I
        at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parse(UnixResolverDnsServerAddressStreamProvider.java:181)
        at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.<init>(UnixResolverDnsServerAddressStreamProvider.java:93)
        at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.<init>(UnixResolverDnsServerAddressStreamProvider.java:127)
        at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parseSilently(UnixResolverDnsServerAddressStreamProvider.java:69)
        at io.netty.resolver.dns.DnsServerAddressStreamProviders$1.provider(DnsServerAddressStreamProviders.java:55)
        at io.netty.resolver.dns.DnsServerAddressStreamProviders$1.<init>(DnsServerAddressStreamProviders.java:34)
        at io.netty.resolver.dns.DnsServerAddressStreamProviders.<clinit>(DnsServerAddressStreamProviders.java:32)
        at io.netty.resolver.dns.DnsNameResolverBuilder.<init>(DnsNameResolverBuilder.java:58)
        at io.netty.resolver.dns.DnsAddressResolverGroup.<init>(DnsAddressResolverGroup.java:54)
        at io.netty.resolver.dns.RoundRobinDnsAddressResolverGroup.<init>(RoundRobinDnsAddressResolverGroup.java:44)
        at com.eatthepath.pushy.apns.ApnsChannelFactory.<init>(ApnsChannelFactory.java:102)
        at com.eatthepath.pushy.apns.ApnsClient.<init>(ApnsClient.java:149)
        at com.eatthepath.pushy.apns.ApnsClientBuilder.build(ApnsClientBuilder.java:566)
`

Note: We are using JDK SSL provider. If I attempt to use netty-native as hinted on your web page, it complains about unsupported format of .p12 file or something like that.

There is no explicit inclusion of any other Netty version in our pom.xml, but I know that some other components do include it for their own purposes. However, we are building a "uber-jar" using maven-assembly-plugin and there was no conflicts before.

**Comment by voodoo84** [comment]
It turns out that it was Netty version conflict. I upgraded the other netty-relying library, which in turn upgraded Netty internally, and there is no NoSuchMethodError exceptions anymore.

Funnily, if I explicitly include Netty version needed for Pushy, it conflicts with the other library.
